[package]
name = "game"
version = "0.0.1-infdev"
edition = "2024"


[dependencies]
bevy-inspector-egui.workspace = true
bevy_rapier2d.workspace = true 
debug_utils = {workspace = true, features = ["debug_overlay"] }
pixel_utils.workspace = true
bevy = {workspace = true, features = ["dynamic_linking"]}
utils = { version = "0.1.0", path = "../libs/utils" }
shaders = { version = "0.1.0", path = "../libs/shaders" }

[[bin]]
name = "game"
path = "src/main.rs"

[[bin]]
name = "shaders"
path = "src/shaders.rs"

[[bin]]
name = "clear"
path = "src/clear.rs"

[[bin]]
name = "tiled"
path = "src/tiled.rs"
